name: pigeon_build_runner
description: Seamlessly integrate pigeon with build_runner for efficient code generation and streamlined development.
publish_to: none
version: 2.0.1

environment:
  sdk: '>=3.11.5 <4.0.0'

dependencies:
  build: ^4.0.6
  pigeon: ">=26.0.0"
  scratch_space: ^1.0.0
  path: ^1.8.3
  pigeon_build_core:
    path: ../pigeon_build_core
  pigeon_build_config:
    path: ../pigeon_build_config

dev_dependencies:
  lints: ^2.0.0
  test: ^1.31.0
